[package]
name = "rust-jemalloc-wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jemalloc-sys = "0.5.3"

[lib]
crate-type=["cdylib"]
